import type { Metadata } from "next";
import Link from "next/link";
import { AssetArt, StoryArt } from "@/components/product-art";
import { assets } from "@/lib/mock-data";
import { absoluteUrl } from "@/lib/site";
export const metadata: Metadata = { title: "PLOTA — A small studio. Many possibilities.", description: "An independent collection of creative tools, original webtoons, and small learning experiments.", alternates: { canonical: "/en", languages: { en: absoluteUrl("/en"), "x-default": absoluteUrl("/en") } }, openGraph: { title: "PLOTA — A small studio. Many possibilities.", description: "Creative tools, original stories, and small everyday discoveries.", url: "/en", locale: "en_US" } };
export default function HomePage() {
  return <div className="hub-body" lang="en"><section className="hub-hero"><div><p className="eyebrow"><span className="status-dot" /> AN INDEPENDENT DIGITAL STUDIO</p><h1>Curiosity takes<br /><em>different shapes.</em></h1></div><p>Tools to make worlds.<br />Stories to get lost in.<br />Small ways to learn something new.<br />Welcome to our little corner of the internet.</p></section><section className="project-grid" aria-label="Our projects"><Link className="project-card" href="/en/fbx"><div className="project-meta"><span>01 / CREATE & BUILD</span><span>↗</span></div><div className="project-visual"><AssetArt asset={assets[0]} /></div><h2>FBX Studio</h2><p>From a small idea to your next game. Creation concepts and assets for Roblox &amp; OVERDARE.</p><span className="text-link">Enter the studio ↗</span></Link><Link className="project-card" href="/en/webtoon"><div className="project-meta"><span>02 / READ & WANDER</span><span>↗</span></div><div className="project-visual"><StoryArt title="A night train beneath the moon" /></div><h2>PLOTA Stories</h2><p>Original webtoons for the quiet moments. A new world is only a chapter away.</p><span className="text-link">Find your next story ↗</span></Link><Link className="project-card" href="/ko/chinese"><div className="project-meta"><span>03 / LEARN A LITTLE</span><span>KO ↗</span></div><div className="project-visual chinese-visual"><strong lang="zh-Hans">你好。</strong><span>Nǐ hǎo</span><small lang="ko">하루 한마디, 새로운 세상.</small></div><h2>한마디 Chinese</h2><p>A little Mandarin, every day. Bite-sized lessons and practice for Korean speakers.</p><span className="text-link">Start a small habit ↗</span></Link></section><section className="hub-bottom"><div><p className="eyebrow">ALWAYS A WORK IN PROGRESS</p><p>These are our first editions. Explore, play, and see what is taking shape.</p></div><Link href="/en/devlog" className="text-link">Notes from the studio ↗</Link></section></div>;
}
